dbt_taxi_project:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: chicagotaxitrips-431912
      dataset: "dbt_taxi_trips"
      location: US
      keyfile: /home/airflow/gcs/data/chicagotaxitrips-431912-db52c7c311c7.json
      threads: 4
      priority: interactive
      job_execution_timeout_seconds: 300
      job_retries: 1
  target: dev
