-- models/dim_holiday.sql

WITH holiday_data AS (
    SELECT * FROM UNNEST([
        STRUCT('2018-01-01' AS holiday_date, 'New Year Day' AS holiday_name),
        STRUCT('2018-01-15' AS holiday_date, 'Martin Luther King Jr. Day' AS holiday_name),
        STRUCT('2018-02-19' AS holiday_date, 'Presidents Day' AS holiday_name),
        STRUCT('2018-05-28' AS holiday_date, 'Memorial Day' AS holiday_name),
        STRUCT('2018-07-04' AS holiday_date, 'Independence Day' AS holiday_name),
        STRUCT('2018-09-03' AS holiday_date, 'Labor Day' AS holiday_name),
        STRUCT('2018-10-08' AS holiday_date, 'Columbus Day' AS holiday_name),
        STRUCT('2018-11-12' AS holiday_date, 'Veterans Day (observed)' AS holiday_name),
        STRUCT('2018-11-22' AS holiday_date, 'Thanksgiving Day' AS holiday_name),
        STRUCT('2018-12-25' AS holiday_date, 'Christmas Day' AS holiday_name),
        STRUCT('2019-01-01' AS holiday_date, 'New Year Day' AS holiday_name),
        STRUCT('2019-01-21' AS holiday_date, 'Martin Luther King Jr. Day' AS holiday_name),
        STRUCT('2019-02-18' AS holiday_date, 'Presidents Day' AS holiday_name),
        STRUCT('2019-05-27' AS holiday_date, 'Memorial Day' AS holiday_name),
        STRUCT('2019-07-04' AS holiday_date, 'Independence Day' AS holiday_name),
        STRUCT('2019-09-02' AS holiday_date, 'Labor Day' AS holiday_name),
        STRUCT('2019-10-14' AS holiday_date, 'Columbus Day' AS holiday_name),
        STRUCT('2019-11-11' AS holiday_date, 'Veterans Day' AS holiday_name),
        STRUCT('2019-11-28' AS holiday_date, 'Thanksgiving Day' AS holiday_name),
        STRUCT('2019-12-25' AS holiday_date, 'Christmas Day' AS holiday_name),
        STRUCT('2020-01-01' AS holiday_date, 'New Year Day' AS holiday_name),
        STRUCT('2020-01-20' AS holiday_date, 'Martin Luther King Jr. Day' AS holiday_name),
        STRUCT('2020-02-17' AS holiday_date, 'Presidents Day' AS holiday_name),
        STRUCT('2020-05-25' AS holiday_date, 'Memorial Day' AS holiday_name),
        STRUCT('2020-07-04' AS holiday_date, 'Independence Day' AS holiday_name),
        STRUCT('2020-09-07' AS holiday_date, 'Labor Day' AS holiday_name),
        STRUCT('2020-10-12' AS holiday_date, 'Columbus Day' AS holiday_name),
        STRUCT('2020-11-11' AS holiday_date, 'Veterans Day' AS holiday_name),
        STRUCT('2020-11-26' AS holiday_date, 'Thanksgiving Day' AS holiday_name),
        STRUCT('2020-12-25' AS holiday_date, 'Christmas Day' AS holiday_name),
        STRUCT('2021-01-01' AS holiday_date, 'New Year Day' AS holiday_name),
        STRUCT('2021-01-18' AS holiday_date, 'Martin Luther King Jr. Day' AS holiday_name),
        STRUCT('2021-02-15' AS holiday_date, 'Presidents Day' AS holiday_name),
        STRUCT('2021-05-31' AS holiday_date, 'Memorial Day' AS holiday_name),
        STRUCT('2021-07-04' AS holiday_date, 'Independence Day' AS holiday_name),
        STRUCT('2021-09-06' AS holiday_date, 'Labor Day' AS holiday_name),
        STRUCT('2021-10-11' AS holiday_date, 'Columbus Day' AS holiday_name),
        STRUCT('2021-11-11' AS holiday_date, 'Veterans Day' AS holiday_name),
        STRUCT('2021-11-25' AS holiday_date, 'Thanksgiving Day' AS holiday_name),
        STRUCT('2021-12-24' AS holiday_date, 'Christmas Day (observed)' AS holiday_name),
        STRUCT('2022-01-01' AS holiday_date, 'New Year Day (observed)' AS holiday_name),
        STRUCT('2022-01-17' AS holiday_date, 'Martin Luther King Jr. Day' AS holiday_name),
        STRUCT('2022-02-21' AS holiday_date, 'Presidents Day' AS holiday_name),
        STRUCT('2022-05-30' AS holiday_date, 'Memorial Day' AS holiday_name),
        STRUCT('2022-07-04' AS holiday_date, 'Independence Day' AS holiday_name),
        STRUCT('2022-09-05' AS holiday_date, 'Labor Day' AS holiday_name),
        STRUCT('2022-10-10' AS holiday_date, 'Columbus Day' AS holiday_name),
        STRUCT('2022-11-11' AS holiday_date, 'Veterans Day' AS holiday_name),
        STRUCT('2022-11-24' AS holiday_date, 'Thanksgiving Day' AS holiday_name),
        STRUCT('2022-12-25' AS holiday_date, 'Christmas Day (observed)' AS holiday_name),
        STRUCT('2023-01-01' AS holiday_date, 'New Year Day (observed)' AS holiday_name),
        STRUCT('2023-01-16' AS holiday_date, 'Martin Luther King Jr. Day' AS holiday_name),
        STRUCT('2023-02-20' AS holiday_date, 'Presidents Day' AS holiday_name),
        STRUCT('2023-05-29' AS holiday_date, 'Memorial Day' AS holiday_name),
        STRUCT('2023-07-04' AS holiday_date, 'Independence Day' AS holiday_name),
        STRUCT('2023-09-04' AS holiday_date, 'Labor Day' AS holiday_name),
        STRUCT('2023-10-09' AS holiday_date, 'Columbus Day' AS holiday_name),
        STRUCT('2023-11-10' AS holiday_date, 'Veterans Day (observed)' AS holiday_name),
        STRUCT('2023-11-23' AS holiday_date, 'Thanksgiving Day' AS holiday_name),
        STRUCT('2023-12-25' AS holiday_date, 'Christmas Day' AS holiday_name),
        STRUCT('2024-01-01' AS holiday_date, 'New Year Day' AS holiday_name)
    ])
)
SELECT
    holiday_date,
    holiday_name
FROM
    holiday_data
