
version: 2

models:

   
          
  - name: daily_taxi_trips
    description: "daily_taxi_trips"
    columns:
      - name: tdate
        description: "The taxi working date"
        data_tests:
          - not_null
          
  
         

  