dbt_taxi_project:
  outputs:
    dev:
      dataset: "dbt_taxi_trips"
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: C:\chicagotaxitrips-431912-db52c7c311c7.json
      location: US
      method: service-account
      priority: interactive
      project: chicagotaxitrips-431912
      threads: 4
      type: bigquery
  target: dev

