name: Deploy DAGs to Cloud Composer

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        version: 'latest'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: chicagotaxitrips-431912

    - name: Upload DAGs to Cloud Composer
      run: |
        gsutil cp -r dags/* gs://us-central1-composortaxi-b32cfc72-bucket/dags/
        gsutil cp -r plugins/* gs://us-central1-composortaxi-b32cfc72-bucket/plugins/
